receipt/urls.py
from django.urls import path
from receipt.views import receipt_view

urlpatterns = [
    path('', receipt_view, name='receipt'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('customer.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('manage-site/', include('manage_site.urls')),
    path('about/', include('about.urls')),
    path('manage-account/', include('manage_account.urls')),
    path('appointments/', include('appointment.urls')),
    path('services/', include('service.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('unauthorized/', include('common.urls')),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('receipts/', include('receipt.urls')),
    path('review/', include('review.urls')),
    path('testimonials/', include('testimonial.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('gallery/', include('gallery.urls')),
    path('blog/', include('blog.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

receipt/models.py
from django.db import models

# Create your models here.
class Receipt(models.Model):
    user = models.ForeignKey('customer.CustomerProfile', on_delete=models.CASCADE)
    product = models.ManyToManyField('product.Product', through='ReceiptProduct')
    total_price = models.IntegerField(default=0)

class ReceiptProduct(models.Model):
    receipt = models.ForeignKey('Receipt', on_delete=models.CASCADE)
    product = models.ForeignKey('product.Product', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

receipt/views.py
from django.shortcuts import render
from .models import Receipt
from customer.models import CustomerProfile
from decorators import user_required, admin_required

# Create your views here.
@user_required
def receipt_view(request):
    receipts = Receipt.objects.filter(user=CustomerProfile.objects.get(user=request.user))
    context = {
        'receipts': receipts[::-1],
    }
    return render(request, 'receipt.html', context)

@admin_required
def receipt_admin_view(request):
    receipts = Receipt.objects.all()
    context = {
        'receipts': receipts[::-1],
    }
    return render(request, 'receipt_admin.html', context)

receipt/templates/receipt.html
{% extends 'common/base.html' %}

{% block title%}Receipts{% endblock%}

{% block content %}

<div class='container'>
    <div class='row justify-content-center'>
        <h1>My Receipts</h1>
    </div>
    {% if not receipts %}
        <h1>You have no receipts! Why don't you buy something?</h1>
        <h5><a href="{% url 'product-type'%}">Browse our products page</a></h5>
    {% else %}
    <div class='row justify-content-center'>
        {% for receipt in receipts %}
        <div class='col-lg-4 col-md-6 col-sm-12'>
            <div class='card p-2 display-card'>
                {% for item in receipt.receiptproduct_set.all %}
                <div class='card-body pb-0 mb-0 pt-0 mb-0'>
                    <p class='p-0 m-0'>{{ item.quantity }}x {{ item.product.name }}
                        <span class='pull-right'>
                        {% if item.product.discounted_price %}
                        {{ item.product.discounted_price }}$
                        {% else %}
                        {{ item.product.price }}$
                        {% endif %}
                        </span>
                    </p>
                </div>
                <hr class='m-1'>
                {% endfor %}
                <div class='card-body'>
                    <p class='p-0 m-0'><strong>Total Price<span class='pull-right'>{{ receipt.total_price }}$</span></strong></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>

{% endblock %}

receipt/templates/receipt_admin.html
{% extends 'common/base.html' %}

{% block title%}Receipts{% endblock%}

{% block content %}

<div class='container'>
    <div class='row justify-content-center'>
        <h1>All Receipts</h1>
    </div>
    {% if not receipts %}
        <h1 class='text-center'>No Receipts Yet</h1>
        <h5 class='text-center'><a href="{% url 'manage-site'%}">Back to Manage Site</a></h5>
    {% else %}
    <div class='row justify-content-center'>
        {% for receipt in receipts %}
        <div class='col-lg-4 col-md-6 col-sm-12'>
            <div class='card p-2 display-card'>
                <div class='card-body pb-0 mb-3 pt-0 mb-0'>
                    <h5 class='p-0 m-0'>{{ receipt.user.user.first_name }} {{ receipt.user.user.last_name }}</h5>
                    <p class='p-0 m-0'>{{ receipt.user.user.username }}</p>                    
                </div>
                <hr class='m-1'>
                {% for item in receipt.receiptproduct_set.all %}
                <div class='card-body pb-0 mb-0 pt-0 mb-0'>
                    <p class='p-0 m-0'>{{ item.quantity }}x {{ item.product.name }}
                        <span class='pull-right'>
                        {% if item.product.discounted_price %}
                        {{ item.product.discounted_price }}K Rwf
                        {% else %}
                        {{ item.product.price }}K Rwf
                        {% endif %}
                        </span>
                    </p>
                </div>
                <hr class='m-1'>
                {% endfor %}
                <div class='card-body'>
                    <p class='p-0 m-0'><strong>Total Price<span class='pull-right'>{{ receipt.total_price }}$</span></strong></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>

{% endblock %}